# Generated by Django 4.2.2 on 2023-06-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_t', models.CharField(max_length=50)),
                ('date_cr', models.DateField()),
                ('n_post', models.IntegerField()),
                ('n_view', models.IntegerField()),
                ('n_like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('pat_name', models.CharField(max_length=20)),
                ('nick', models.CharField(max_length=20)),
                ('date_reg', models.DateField()),
                ('date_b', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('n_post', models.IntegerField()),
                ('n_view', models.IntegerField()),
                ('n_like', models.IntegerField()),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_post', models.DateField()),
                ('n_view', models.IntegerField()),
                ('n_like', models.IntegerField()),
                ('n_comm', models.IntegerField()),
                ('id_topic', models.ManyToManyField(to='main.topics')),
                ('id_author', models.ManyToManyField(to='main.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('n_like', models.IntegerField()),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.posts')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.users')),
            ],
        ),
    ]
