# Generated by Django 4.2.2 on 2023-08-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='id_author',
            field=models.ManyToManyField(related_name='authors', to='main.authors'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id_topic',
            field=models.ManyToManyField(related_name='topics', to='main.topics'),
        ),
    ]
