# Generated by Django 4.2.2 on 2023-08-10 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_posts_id_author_alter_posts_id_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
